data_paths:
  raw_data: "data/hmQOVnDvRN.xls"
  processed_data: "data/processed/processed_data.csv"
  artifacts_dir: "artifacts"
  data_artifacts_dir: "artifacts/data"
  model_artifacts_dir: "artifacts/models"

columns:
  target: "Churn"
  drop_columns: 
    - "customerID"
    - "gender"
    - "SeniorCitizen"
    - "Partner"
    - "Dependents"
    - "PhoneService"
    - "MultipleLines"
    - "OnlineBackup"
    - "DeviceProtection"
    - "StreamingTV"
    - "StreamingMovies"
    - "PaperlessBilling"
  feature_groups:
    demographics:
      - "gender"
      - "SeniorCitizen"
      - "Partner"
      - "Dependents"
    account_info:
      - "tenure"
      - "Contract"
      - "PaperlessBilling"
      - "PaymentMethod"
    services:
      - "PhoneService"
      - "MultipleLines"
      - "InternetService"
      - "OnlineSecurity"
      - "OnlineBackup"
      - "DeviceProtection"
      - "TechSupport"
      - "StreamingTV"
      - "StreamingMovies"
    financials:
      - "MonthlyCharges"
      - "TotalCharges"

missing_values:
  strategies:
    total_charges:
      method: "mean"
    binary_features:
      method: "mode"
    categorical_features:
      method: "mode"
  binary_encoding:
    OnlineSecurity: "OnlineSecurity_numeric"
    TechSupport: "TechSupport_numeric"
  columns_to_impute:
    numeric: ["TotalCharges"]
    categorical: ["OnlineSecurity_numeric", "TechSupport_numeric"]

feature_engineering:
  services_score:
    services:
      - "OnlineSecurity"
      - "TechSupport"
      - "OnlineBackup"
      - "DeviceProtection"
  vulnerability_score:
    weights:
      senior_citizen: 2
      no_partner: 1
      no_dependents: 1
      month_to_month: 2
      new_customer: 2
    tenure_threshold: 12

feature_binning:
  tenure:
    bins: [0, 12, 24, 48, 72]
    labels: ["New", "Intermediate", "Established", "Loyal"]
  spend:
    bins: [0, 50, 100, 200, null]  # null represents infinity
    labels: ["Low", "Medium", "High", "Extreme"]

feature_encoding:
  binary_mapping:
    "No": 0
    "Yes": 1
  nominal_features:
    - "InternetService"
    - "Contract"
    - "PaymentMethod"
  ordinal_features:
    - "tenure_group"
    - "Vulnerability_Score"
    - "Services_Score"
  ordinal_mappings:
    tenure_group:
      "New": 0
      "Intermediate": 1
      "Established": 2
      "Loyal": 3

feature_scaling:
  numeric_features:
    - "TotalCharges"
    - "MonthlyCharges"
  scaler_type: "standard"  # options: standard, minmax, robust

data_splitting:
  test_size: 0.2
  random_state: 42

model_training:
  models:
    random_forest:
      param_grid:
        n_estimators: [100, 200, 300]
        max_depth: [10, 15, 20]
        min_samples_split: [2, 5, 10]
        max_features: ["sqrt", "log2"]
        criterion: ["gini", "entropy"]
    xgboost:
      param_grid:
        learning_rate: [0.01, 0.1, 0.2]
        max_depth: [3, 6, 9]
        n_estimators: [100, 200, 300]
        subsample: [0.8, 0.9, 1.0]
        colsample_bytree: [0.8, 0.9, 1.0]
    catboost:
      param_grid:
        learning_rate: [0.01, 0.1, 0.2]
        depth: [4, 6, 8]
        iterations: [100, 200, 300]
        l2_leaf_reg: [1, 3, 5]
        border_count: [32, 64, 128]
  cv_folds: 5
  scoring: "roc_auc"
  n_jobs: -1

class_balancing:
  method: "smote"
  random_state: 42

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1-score"
    - "roc_auc"
  output_dir: "artifacts/evaluation"

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
